### ISSUE TITLE
Lower setup complexity by setting useful default values

### ISSUE THREAD

**Issue by chrboehm** [bakdata/citus-k8s-membership-manager#27]
see e.g.,
```yaml
volumeMounts:
    - name: citus-config-mount
      mountPath: /etc/citus-config
```
